---
- hosts: all
  become: yes
  tasks:
  
    - name: stop current running container
      command: docker stop simple-devops-container
      ignore_errors: yes
      
    - name: remove stopped container
      command: docker rm simple-devops-container
      ignore_errors: yes
      
    - name: remove current docker image
      command: docker rmi vdbsrao/simple-devops-image:latest
      ignore_errors: yes
      
    - name: pull docker image from dockerhub
      command: docker pull vdbsrao/simple-devops-image:latest
      ignore_errors: yes
      
    - name: creating docker container using simple -devops -imsge
      command: docker run -d --name simple-devops-container -p 8080:8080 vdbsrao/simple-devops-image:latest
      ignore_errors: yes
      
